# This file lists objects / models which are relevant for the competition

Objects:
    Banana:
        package: "some_pkg"
        model_path: "models/banana.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.


Places:
    OnTheCounter: # offset Pose
        position:
            x: 0.
            y: 0.
            z: 0.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.




