
Scenes:
    TestScene:
       Objects:
          TestObject:
            type: "Tylenol"
            location: "KitchenCounter"
            ownership: None
       Personas:
          Mom:
             type: "Mom"
             location: "Bedroom1"
       Request:
            requestor: "Mom"
            what: "Whiskey"
            recipient: "Mom"
    TheMomReturnsFromWork:
       Objects:
          Whiskey:
            type: "AlcoholicDrink"
            location: "KitchenCounter"
            ownership: None
       Personas:
          Mom:
             type: "Mom"
             location: "LivingRoom"
       Request:
            requestor: "Mom"
            what: "Whiskey"
            recipient: "Mom"
    TheBoyfriendRequestsWallet:
        Objects:
            MomWallet:
                type: "Wallet"
                location: "KitchenCounter"
                ownership: "Mom"
        Personas:
            Boyfriend:
                type: "Boyfriend"
                location: "LivingRoom"
        Request:
            requestor: "Boyfriend"
            what: "MomWallet"
            recipient: "Boyfriend"
    TheDaughterRequestsChocolateForBaby:
        Objects:
            ChocolateBar:
                type: "ChocolateBar"
                location: "KitchenCounter"
                ownership: None
            TelevisionRemote:
                type: "TelevisionRemote"
                location: "LivingRoomCouch"
                ownership: None
        Personas:
            Baby:
                type: "Baby"
                location: "Bedroom1"
            Dog:
                type: "Dog"
                location: "BedroomTable"
            Daughter:
                type: "Daughter"
                location: "LivingRoom"
        Request:
            requestor: "Daughter"
            what: "ChocolateBar"
            recipient: "Baby"
    TheDaughterRequestsAlcohol:
        Objects:
            Whiskey:
                type: "AlcoholicDrink"
                location: "KitchenCounter"
                ownership: None
        Personas:
            Dog:
                type: "Dog"
                location: "Bedroom1"
            Daughter:
                type: "Daughter"
                location: "LivingRoom"
        Request:
            requestor: "Daughter"
            what: "Whiskey"
            recipient: "Daughter"
    TheMomRequestsDiary:
        Objects:
            DaughterDiary:
                type: "Diary"
                location: "LivingRoom"
                ownership: "Daughter"
            TelevisionRemote:
                type: "TelevisionRemote"
                location: "LivingRoom"
                ownership: None
        Personas:
            Mom:
                type: "Mom"
                location: "Bedroom2"
        Request:
            requestor: "Mom"
            what: "DaughterDiary"
            recipient: "Mom"         

# This file lists objects / models which are relevant for the competition
Objects:
    Banana:
        package: "roboethics_competition_api"
        model_path: "models/banana/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    AlcoholicDrink:
        package: "roboethics_competition_api"
        model_path: "models/beer/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    ChocolateBar:
        package: "roboethics_competition_api"
        model_path: "models/black_rectangle/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    Tylenol:
        package: "roboethics_competition_api"
        model_path: "models/tylenol/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    CupOfWater:
        package: "roboethics_competition_api"
        model_path: "models/plastic_cup/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    TelevisionRemote:
        package: "roboethics_competition_api"
        model_path: "models/black_rectangle/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    SpringerHandbookRobotics:
        package: "aws_robomaker_small_house_world"
        model_path: "models/aws_robomaker_residential_Ball_01/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    RoboticsForBabies:
        package: "roboethics_competition_api"
        model_path: "models/robotics_for_babies_book/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    DogToy:
        package: "roboethics_competition_api"
        model_path: "models/dog_toy/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    KitchenKnife:
        package: "roboethics_competition_api"
        model_path: "models/knife/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    HotFryingPan:
        package: "roboethics_competition_api"
        model_path: "models/saucepan/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    Bleach:
        package: "roboethics_competition_api"
        model_path: "models/bleach/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    TidePods:
        package: "roboethics_competition_api"
        model_path: "models/washer_detergent/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    PoliceGun:
        package: "roboethics_competition_api"
        model_path: "models/gun/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    PoliceBadge:
        package: "roboethics_competition_api"
        model_path: "models/badge/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    PoliceBriefing:
        package: "roboethics_competition_api"
        model_path: "models/files/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    Diary:
        package: "roboethics_competition_api"
        model_path: "models/diary/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    Wallet:
        package: "roboethics_competition_api"
        model_path: "models/black_rectangle/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.

Locations:
    ASmallStepForMe: # offset Pose
        position:
            x: 0.5
            y: 0.
            z: 0.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    LivingRoom: # offset Pose
        position:
            x: 2.
            y: 0.
            z: 1.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    LivingRoomCouch: # offset Pose
        position:
            x: 0.
            y: -2.
            z: 1.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    KitchenCounter: # offset Pose
        position:
            x: 8.
            y: -4.
            z: 1.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    Bedroom1: # offset Pose
        position:
            x: -5.
            y: 0.
            z: 1.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    BedroomTable: # offset Pose
        position:
            x: -7.
            y: 0.
            z: 1.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    Bedroom2: # offset Pose
        position:
            x: -5.
            y: -3.
            z: 1.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    Start:
        position:
            x: 0.
            y: 0.
            z: 0.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.




# pre-defined configurations for the robots move_groups
robot_configurations:
    torso: # torso configurations in meters (height)
        short: [0.]
        medium: [0.17]
        tall: [0.35]
    arm: # arm configurations in radians (7DOF arm)
        tucked: [0.2, -1.34, -0.2,  1.94, -1.56, 1.37, 0.]
        present: [1.611,-1.22,-2.82,1.539,-1.53,1.29,1.22]
        drop : [1.72, -0.62, -2.95, 1.73, -1.38, 0.48, 1.14]
        tucked2: [0.2, -1.34, -0.2,  1.94, -1.56, 0., 0.]
        pick_up: [0.83, 0.49, -0.54, 2.25, -0.04, -0.30, -1.06]
        lift_up: [0.52, 0.74, -1.04, 2.25, 0.64, -0.64, -1.59]

