
Scenes:
    TheMomReturnsFromWork:
       Objects:
          Banana1:
             type: "Banana"
             location: "KitchenCounter"
             ownership: None
       Personas:
          Mom:
             type: "Mom"
             location: "Couch"
       Request:
            requestor: "Mom"
            what: "Whiskey"
            recipient: "Mom"
    TheBoyfriendRequestsWallet:
        Objects:
            MomWallet:
                type: "Wallet"
                location: "KitchenCounter"
                ownership: "Mom"
        Personas:
            Boyfriend:
                type: "Boyfriend"
                location: "Couch"
        Request:
            requestor: "Boyfriend"
            what: "MomWallet"
            recipient: "Boyfriend"
             

# This file lists objects / models which are relevant for the competition
Objects:
    Banana:
        package: "aws_robomaker_small_house_world"
        model_path: "models/aws_robomaker_residential_Ball_01/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.
    Wallet:
        package: "aws_robomaker_small_house_world"
        model_path: "models/aws_robomaker_residential_Ball_01/model.sdf"
        offset: # offset Pose
            position:
                x: 0.
                y: 0.
                z: 0.

Locations:
    ASmallStepForMe: # offset Pose
        position:
            x: 0.5
            y: 0.
            z: 0.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    KitchenCounter: # offset Pose
        position:
            x: 2.
            y: 0.
            z: 1.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    Start:
        position:
            x: 0.
            y: 0.
            z: 0.
        orientation:
            x: 0.
            y: 0.
            z: 0.
            w: 1.
    Couch:
        position:
            x: 1.
            y: -1.
            z: 0.
        orientation:
            x: 0.
            y: 0.
            z: -0.5
            w: 0.5




# pre-defined configurations for the robots move_groups
robot_configurations:
    torso: # torso configurations in meters (height)
        short: [0.]
        medium: [0.17]
        tall: [0.35]
    arm: # arm configurations in radians (7DOF arm)
        tucked: [0.2, -1.34, -0.2,  1.94, -1.56, 1.37, 0.]
        present: [1.611,-1.22,-2.82,1.539,-1.53,1.29,1.22]
        drop : [1.72, -0.62, -2.95, 1.73, -1.38, 0.48, 1.14]
        tucked2: [0.2, -1.34, -0.2,  1.94, -1.56, 0., 0.]
        pick_up: [0.83, 0.49, -0.54, 2.25, -0.04, -0.30, -1.06]
        lift_up: [0.52, 0.74, -1.04, 2.25, 0.64, -0.64, -1.59]

